package com.brassbeluga.managers;

public enum DownloadAction {
	TRACKS_CHANGED, USERNAME_CHANGED, DOWNLOAD_PATH_CHANGED, 
		LIKES_CHANGED, LIKES_FINISHED, LIKES_CLEARED, SONG_PROGRESS, DOWNLOADS_FINISHED;
}
